# Generated by Django 5.1.15 on 2026-09-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_slots', to='chores.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chores.member')),
            ],
            options={
                'ordering': ['chore', 'position'],
                'constraints': [models.UniqueConstraint(fields=('chore', 'position'), name='unique_position_per_chore'), models.UniqueConstraint(fields=('chore', 'member'), name='unique_member_per_chore')],
            },
        ),
    ]
