# Generated by Django 5.1.15 on 2026-09-09 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_rotationslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_key', models.CharField(max_length=16)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chores.member')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
