# Generated by Django 5.1.15 on 2026-09-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='chores.chore')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_out', to='chores.member')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swaps_in', to='chores.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('chore', 'period_key'), name='unique_swap_per_chore_period'), models.CheckConstraint(condition=models.Q(('from_member', models.F('to_member')), _negated=True), name='swap_from_member_ne_to_member')],
            },
        ),
    ]
